<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class UserControllerTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
    }

    public function test_it_can_create_a_user()
    {
        $user = User::factory()->raw();

        $this->post(route('users.store'), $user)->assertSuccessful();

        $this->assertDatabaseHas('users', [
            'email' => $user['email'],
        ]);
    }

    public function test_it_can_login_as_user()
    {
        $password = 'snickers';
        $user = User::factory()->raw([
            'password' => $password,
        ]);

        $this->post(route('users.store'), $user)->assertSuccessful();

        $this->assertDatabaseHas('users', [
            'email' => $user['email'],
        ]);

        $this->post(route('users.login'), [
            'email' => $user['email'],
            'password' => $user['password'],
        ])->assertRedirect('/');

        $this->assertAuthenticatedAs(User::query()->where('email', $user['email'])->firstOrFail());
    }
}
