<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use PhpParser\Node\Scalar\String_;

class Alcohol extends Model
{
    public const FORMATTED_CATEGORIES = [
        "Produits",
        "Products",
        "Produits|Vin",
        "Products|Wine",
        "Produits|Vin|Vin rouge",
        "Products|Wine|Red Wine",
        "Produits|Vin|Vin blanc",
        "Products|Wine|White Wine",
        "Collections",
        "Products|Beer & Cider",
        "Produits|Bière et cidre",
        "Products|Spirits",
        "Produits|Spiritueux",
        "Vintages",
        "Products|Beer & Cider|Ale",
        "Produits|Bière et cidre|Ale",
        "Collections|Collection Destination monde",
        "Collections|Destination Collection",
        "Collections|Collection Destination monde|Toutes les collections Destination monde",
        "Collections|Destination Collection|Shop All Destination Collection",
        "Products|Spirits|Whisky",
        "Produits|Spiritueux|Whisky",
        "Products|Beer & Cider|Lager",
        "Produits|Bière et cidre|Lager",
        "Products|Wine|Rose Wine",
        "Produits|Vin|Vin rosé",
        "Products|Beer & Cider|Lager|Pale Lager",
        "Produits|Bière et cidre|Lager|Lager pâle",
        "Collections|Vin",
        "Collections|Wine",
        "Products|Wine|Sparkling Wine",
        "Produits|Vin|Vin mousseux",
        "Products|Wine|Sake & Rice Wine",
        "Produits|Vin|Saké",
        "Produits|Vin|Vin fortifié",
        "Products|Wine|Fortified Wine",
        "Vintages|Vintages – Nouveaux arrivages",
        "Collections|Beer & Cider",
        "Products|Spirits|Liqueur",
        "Produits|Spiritueux|Liqueur",
        "Vintages|Vintages New Arrivals",
        "Collections|Bière et cidre",
        "Products|Wine|Sparkling Wine|White Sparkling Wine",
        "Produits|Vin|Vin mousseux|Vin mousseux blanc",
        "Vintages|Classics",
        "Vintages|Classiques",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)",
        "Collections|Occasions",
        "Products|Spirits|Whisky|Scotch Whisky",
        "Produits|Spiritueux|Whisky|Whisky écossais",
        "Collections|Spirits",
        "Products|Beer & Cider|Lager|Pale Lager|North American Lager",
        "Produits|Bière et cidre|Lager|Lager pâle|Lager nord-américaine",
        "Collections|Spiritueux",
        "Collections|Beer & Cider|Ontario Craft Beers",
        "Collections|Bière et cidre|Voir toutes les bieres artisanales de l'ontario",
        "Products|Spirits|Vodka",
        "Produits|Spiritueux|Vodka",
        "Products|Coolers",
        "Produits|Cooler",
        "Promotions",
        "Promotion",
        "Products|Wine|Fortified Wine|Port",
        "Produits|Vin|Vin fortifié|Porto",
        "Produits|Vin|Vin de spécialité",
        "Products|Wine|Specialty Wine",
        "Collections|Vin|Vins en grand format",
        "Produits|Vin|Champagne",
        "Products|Wine|Champagne",
        "Collections|Wine|Large Format Wines",
        "Cadeaux",
        "Gifts",
        "Products|Spirits|Cognac & Brandy",
        "Produits|Spiritueux|Cognac et brandy",
        "Products|Beer & Cider|Ale|Pale Ale",
        "Produits|Bière et cidre|Ale|Ale pâle",
        "Products|Spirits|Vodka|Unflavoured Vodka",
        "Produits|Spiritueux|Vodka|Vodka non aromatisée",
        "Products|Spirits|Gin",
        "Produits|Spiritueux|Gin",
        "New Arrivals",
        "Nouveaux arrivages",
        "Produits|Vin|Champagne|Champagne blanc",
        "Products|Wine|Champagne|White Champagne",
        "Vintages|Vintages - La collection Les essentiels",
        "Vintages|Vintages Essentials Collection",
        "Cadeaux|Prix",
        "Products|Wine|Gifts and Samplers",
        "Produits|Vin|Cadeau et emballage mixte",
        "Products|Beer & Cider|Ale|Sour Ale",
        "Produits|Bière et cidre|Ale|Ale sure",
        "Gifts|Shop by Price",
        "Collections|Coolers",
        "Collections|Cooler",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)|American IPA",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)|IPA américaine",
        "Products|Spirits|Rum",
        "Produits|Spiritueux|Rhum",
        "Products|Wine|Sparkling Wine|Rosé & Red Sparkling Wine",
        "Produits|Vin|Vin mousseux|Vin mousseux rosé et rouge",
        "Products|Spirits|Whisky|Canadian Whisky",
        "Produits|Spiritueux|Whisky|Whisky canadien",
        "Products|Beer & Cider|Cider",
        "Produits|Bière et cidre|Cidre",
        "Products|Spirits|Whisky|American Whiskey & Bourbon",
        "Produits|Spiritueux|Whisky|Whiskey américain et bourbon",
        "Collections|Tendances",
        "Collections|Trends",
        "Products|Spirits|Tequila",
        "Produits|Spiritueux|Tequila",
        "Products|Coolers|Coolers & Cocktails",
        "Produits|Cooler|Cooler et cocktail",
        "Products|Spirits|Liqueur|Sippers & Mixers",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur",
        "Collections|Coolers|Local Coolers",
        "Collections|Cooler|Achetez les produits d’ici",
        "Products|Beer & Cider|Ale|Stout & Porter",
        "Products|Spirits|Gin|Traditional Gin",
        "Produits|Bière et cidre|Ale|Stout et porter",
        "Produits|Spiritueux|Gin|Gin traditionnel",
        "Products|Beer & Cider|Gifts and Samplers",
        "Produits|Bière et cidre|Cadeau et emballage mixte",
        "Products|Spirits|Cognac & Brandy|Brandy",
        "Produits|Spiritueux|Cognac et brandy|Brandy",
        "Collections|Kascher",
        "Collections|Kosher",
        "Collections|LCBO",
        "Vintages|Vintages New Arrivals|July 16 2022",
        "Vintages|Vintages – Nouveaux arrivages|16 juillet 2022",
        "Products|Beer & Cider|Lager|Pale Lager|Light Lager",
        "Products|Spirits|Whisky|Canadian Whisky|Canadian Blended Whisky",
        "Produits|Bière et cidre|Lager|Lager pâle|Lager légère",
        "Produits|Spiritueux|Whisky|Whisky canadien|Whisky d'assemblage canadien",
        "Vintages|Classics|April Classics Collection",
        "Vintages|Classiques|Collection Les Classiques - Avril",
        "Vintages|Classics|May Classics Collection",
        "Vintages|Classiques|Collection Les Classiques - Mai",
        "Products|Beer & Cider|Ale|Flavoured & Spiced Beer",
        "Products|Beer & Cider|Ale|Pale Ale|American Pale Ale",
        "Products|Spirits|Gin|Traditional Gin|London Dry Gin",
        "Produits|Bière et cidre|Ale|Ale pâle|Ale pâle américaine",
        "Produits|Bière et cidre|Ale|Bière aromatisée et bière épicée",
        "Produits|Spiritueux|Gin|Gin traditionnel|London Dry gin",
        "Products|Beer & Cider|Ale|Belgian Ale",
        "Produits|Bière et cidre|Ale|Ale belge",
        "Collections|Vin|Choix Alleges",
        "Collections|Wine|Lighter Choices Wine",
        "Products|Spirits|Whisky|American Whiskey & Bourbon|Bourbon",
        "Produits|Spiritueux|Whisky|Whiskey américain et bourbon|Bourbon",
        "Products|Spirits|Liqueur|Bitters",
        "Produits|Spiritueux|Liqueur|Amer",
        "Products|Spirits|Whisky|Scotch Whisky|Highland Single Malt Scotch Whisky",
        "Produits|Spiritueux|Whisky|Whisky écossais|Scotch single malt des Highlands",
        "Vintages|Livraison Vintages 21 mai 2022",
        "Vintages|Vintages Release May 21 2022",
        "Products|Beer & Cider|Gifts and Samplers|Taster Packs",
        "Produits|Bière et cidre|Cadeau et emballage mixte|Carton dégustation de bière et de cidre",
        "Products|Spirits|Grappa",
        "Products|Spirits|Rum|Amber & Dark Rum",
        "Produits|Spiritueux|Grappa",
        "Produits|Spiritueux|Rhum|Rhum ambré ou brun",
        "Vintages|Vintages New Arrivals|June 18 2022",
        "Vintages|Vintages – Nouveaux arrivages|18 juin 2022",
        "Products|Beer & Cider|Lager|Pale Lager|European Lager",
        "Produits|Bière et cidre|Lager|Lager pâle|Lager européenne",
        "Collections|Occasions|Caribbean Carnival",
        "Vintages|Vintages – Nouveaux arrivages|16 avril 2022",
        "Collections|Kosher Wine",
        "Collections|Vin Kascher",
        "Vintages|Vintages New Arrivals|April 30 2022",
        "Vintages|Vintages – Nouveaux arrivages|30 avril 2022",
        "Collections|Spirits|Whisky Shop",
        "Collections|Spiritueux|Boutique De Whisky",
        "Collections|Vin|Festival des vins de Toronto",
        "Collections|Wine|Wine Fest Toronto",
        "Products|Beer & Cider|Cider|Flavoured Cider",
        "Produits|Bière et cidre|Cidre|Cidre aromatisé",
        "Collections|Shop Same Day Pick Up",
        "Collections|Collection Destination monde|Vins naturels et à faible intervention",
        "Products|Coolers|Seltzers & Sodas",
        "Produits|Cooler|Seltzer et soda",
        "Vintages|Classics|July Classics Collection",
        "Vintages|Classiques|Collection Les Classiques - juillet",
        "Products|Spirits|Whisky|Scotch Whisky|Speyside Single Malt Scotch Whisky",
        "Produits|Spiritueux|Whisky|Whisky écossais|Scotch single malt du Speyside",
        "Collections|Destination Collection|Natural and Low Intervention Wines",
        "Vintages|Vintages New Arrivals|April 16 2022",
        "Collections|Vin|Vins en petit format",
        "Collections|Wine|Small Format Wines",
        "Vintages|Vintages - Exclusivités en ligne",
        "Products|Beer & Cider|Ale|Dark Ale",
        "Produits|Bière et cidre|Ale|Ale foncée",
        "Vintages|Classics|June Classics Collection",
        "Vintages|Classiques|Collection Les Classiques - Juin",
        "Products|Coolers|Coolers & Cocktails|Traditional Coolers",
        "Produits|Cooler|Cooler et cocktail|Cooler traditionnel",
        "Products|Wine|Specialty Wine|Flavoured Wine",
        "Produits|Vin|Vin de spécialité|Vin aromatisé",
        "Promotions|LCBO",
        "Promotion|LCBO",
        "New Arrivals|Beers & Ciders",
        "Nouveaux arrivages|Cidres et bières",
        "Products|Beer & Cider|Ale|Wheat Ale",
        "Products|Beer & Cider|Non-Alcoholic & Specialty",
        "Products|Spirits|Liqueur|Cream Liqueur",
        "Products|Wine|Specialty Wine|Dessert Wine",
        "Produits|Bière et cidre|Ale|Ale de blé",
        "Produits|Bière et cidre|Bière de spécialité",
        "Produits|Spiritueux|Liqueur|Boisson à la crème",
        "Produits|Vin|Vin de spécialité|Vin de dessert",
        "Products|Spirits|Whisky|Scotch Whisky|Scotch Blended Whisky",
        "Produits|Spiritueux|Whisky|Whisky écossais|Whisky d'assemblage écossais",
        "Products|Wine|Fortified Wine|Sherry",
        "Produits|Vin|Vin fortifié|Xérès",
        "Products|Spirits|Whisky|Irish Whiskey",
        "Produits|Spiritueux|Whisky|Whiskey irlandais",
        "Products|Spirits|Cognac & Brandy|Cognac",
        "Products|Spirits|Vodka|Flavoured Vodka",
        "Products|Wine|Gifts and Samplers|Mixed Wine Gifts and Samplers",
        "Produits|Spiritueux|Cognac et brandy|Cognac",
        "Produits|Spiritueux|Vodka|Vodka aromatisée",
        "Produits|Vin|Cadeau et emballage mixte|Emballage-cadeau / Emballage mixte de vin",
        "Collections|Occasions|Les Favoris",
        "Collections|Occasions|Summer Moments",
        "Products|Spirits|Liqueur|Baijiu",
        "Produits|Spiritueux|Liqueur|Baijiu",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)|Hazy IPA",
        "Products|Beer & Cider|Ale|Lagered Ale",
        "Products|Beer & Cider|Cider|Traditional Cider",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)|IPA trouble",
        "Produits|Bière et cidre|Ale|Lager-ale",
        "Produits|Bière et cidre|Cidre|Cidre traditionnel",
        "Cadeaux|Prix|Moins de 50 $",
        "Collections|LCBO|Celebrity Products",
        "Collections|LCBO|Produits de noms célèbres",
        "Cadeaux|Cadeaux de mariage",
        "Produits|Vin|Vin fortifié|Vin fortifié du Vieux Continent",
        "Products|Wine|Fortified Wine|European Fortified Wine",
        "Gifts|Shop by Price|Under $50",
        "Gifts|Wedding Gifts",
        "Collections|Occasions|Cadeau pour la fête des pères",
        "Collections|Occasions|Gifts for Father's Day",
        "Products|Beer & Cider|Ale|Flavoured & Spiced Beer|Flavoured Beer",
        "Products|Wine|Icewine",
        "Produits|Bière et cidre|Ale|Bière aromatisée et bière épicée|Bière aromatisée",
        "Produits|Vin|Vin de glace",
        "Products|Beer & Cider|Ale|Sour Ale|Kettle Sour Ale",
        "Produits|Bière et cidre|Ale|Ale sure|Ale surie en chaudière",
        "Products|Wine|Specialty Wine|Vermouth & Aperitif",
        "Produits|Vin|Vin de spécialité|Vermouth et apéritif",
        "Vintages|Vintages - Sélection de vins du week-end",
        "Products|Spirits|Gin|Flavoured Gin",
        "Products|Spirits|Whisky|Scotch Whisky|Islay Single Malt Scotch Whisky",
        "Produits|Spiritueux|Gin|Gin aromatisé",
        "Produits|Spiritueux|Whisky|Whisky écossais|Scotch single malt d'Islay",
        "Promotions|Canadian Made Products Bonus Offer",
        "Promotion|Offres de points-boni fabriqués au canada",
        "Products|Beer & Cider|Lager|Pale Lager|German-Style Pilsner",
        "Produits|Bière et cidre|Lager|Lager pâle|Pilsen de style allemand",
        "Products|Wine|Fortified Wine|Madeira & Marsala",
        "Products|Wine|Gifts and Samplers|Red Wine Gifts and Samplers",
        "Produits|Vin|Cadeau et emballage mixte|Cadeau / Emballage mixte de vin rouge",
        "Produits|Vin|Vin fortifié|Madère et marsala",
        "Products|Spirits|Whisky|Irish Whiskey|Irish Blended Whiskey",
        "Produits|Spiritueux|Whisky|Whiskey irlandais|Whiskey d'assemblage irlandais",
        "Collections|Beer & Cider|Ontario Craft Ciders",
        "Collections|Bière et cidre|Voir tous les cidres de l'ontario",
        "Products|Spirits|Liqueur|Bitters|Herbal Bitters",
        "Produits|Spiritueux|Liqueur|Amer|Amer aux herbes",
        "Vintages|Vintages Weekend Wine Roundup",
        "Collections|Spirits|Ontario Small Distillers",
        "Products|Spirits|Rum|Amber & Dark Rum|Aged Rum",
        "Products|Spirits|Soju",
        "Produits|Spiritueux|Rhum|Rhum ambré ou brun|Rhum vieilli",
        "Produits|Spiritueux|Soju",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)|Session IPA",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)|IPA de soif",
        "Products|Spirits|Cognac & Brandy|Brandy|Fruit Spirit",
        "Produits|Spiritueux|Cognac et brandy|Brandy|Eau-de-vie de fruit",
        "New Arrivals|Spirits",
        "Nouveaux arrivages|Spiritueux",
        "Products|Spirits|Tequila|Reposado Tequila",
        "Produits|Spiritueux|Tequila|Tequila reposado",
        "Cadeaux|Prix|Moins de 100 $",
        "Collections|Vin|Vin en boîte",
        "Collections|Wine|Boxed Wine",
        "Gifts|Shop by Price|Under $100",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)|Double IPA",
        "Products|Beer & Cider|Non-Alcoholic & Specialty|Radler & Shandy",
        "Products|Wine|Gifts and Samplers|Sparkling Wine Gifts and Samplers",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)|Double IPA",
        "Produits|Bière et cidre|Bière de spécialité|Panaché",
        "Produits|Vin|Cadeau et emballage mixte|Cadeau / Emballage mixte de vin mousseux",
        "Products|Wine|Champagne|Rosé Champagne",
        "Produits|Vin|Champagne|Champagne rosé",
        "New Arrivals|Wines",
        "Nouveaux arrivages|Vins",
        "Products|Beer & Cider|Lager|Dark Lager",
        "Produits|Bière et cidre|Lager|Lager foncée",
        "Collections|Shop Same Day Pick Up|Beer & Cider",
        "Products|Wine|Icewine|White Icewine",
        "Produits|Vin|Vin de glace|Vin de glace blanc",
        "Cadeaux|Prix|Cadeaux de luxe",
        "Collections|Shop Same Day Pick Up|Coolers",
        "Gifts|Shop by Price|Luxe Gifts",
        "Products|Beer & Cider|Ale|Belgian Ale|Belgian Saison",
        "Produits|Bière et cidre|Ale|Ale belge|Saison belge",
        "Collections|Spirits|Whisky Shop|Whisky Shop New Arrivals",
        "Collections|Spiritueux|Boutique De Whisky|Nouveautes",
        "Products|Beer & Cider|Ale|Flavoured & Spiced Beer|Fruit Beer",
        "Products|Spirits|Liqueur|Sippers & Mixers|Cocktail Mixers",
        "Products|Spirits|Tequila|Blanco Tequila",
        "Produits|Bière et cidre|Ale|Bière aromatisée et bière épicée|Bière aux fruits",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur|Allongeur",
        "Produits|Spiritueux|Tequila|Tequila blanco",
        "Promotions|One Day Sale",
        "Promotion|Solde d'un jour",
        "Collections|Spirits|Fruit Flavoured Spirits",
        "Collections|Spiritueux|Spiritueux Fruites",
        "Collections|LCBO|Celebrity Products|Spirits",
        "Collections|LCBO|Produits de noms célèbres|Spiritueux",
        "Collections|Spirits|Whisky Shop|Scotch Whisky",
        "Collections|Spiritueux|Boutique De Whisky|Scotch Whisky",
        "Products|Beer & Cider|Ale|Lagered Ale|Kölsch",
        "Produits|Bière et cidre|Ale|Lager-ale|Kölsch",
        "Collections|Spirits|Whisky Shop|Whisky Shop Available Year Round",
        "Collections|Spiritueux|Boutique De Whisky|Produits Offerts A Longueur D'annee",
        "Collections|Vin|Vins à servir lors d’un mariage",
        "Collections|Wine|Wines to Serve at Your Wedding",
        "Products|Beer & Cider|Lager|Amber Lager",
        "Products|Coolers|Coolers & Cocktails|Cocktails",
        "Products|Spirits|Liqueur|Sippers & Mixers|Fruit Flavours",
        "Products|Spirits|Soju|Unflavoured Soju",
        "Produits|Bière et cidre|Lager|Lager ambrée",
        "Produits|Cooler|Cooler et cocktail|Cocktail",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur|Arômes de fruits",
        "Produits|Spiritueux|Soju|Soju non aromatisé",
        "Promotions|Clearance",
        "Promotion|Liquidation",
        "Collections|Vin|Vin rosé",
        "Collections|Wine|Rosé",
        "Products|Beer & Cider|Ale|Sour Ale|Aged Sour Ale",
        "Products|Beer & Cider|Ale|Stout & Porter|Porter",
        "Produits|Bière et cidre|Ale|Ale sure|Ale sure vieillie",
        "Produits|Bière et cidre|Ale|Stout et porter|Porter",
        "Vintages|Exclusivités en ligne",
        "Vintages|Online Exclusives",
        "Vintages|Vintages New Arrivals|June 30 2022",
        "Vintages|Vintages – Nouveaux arrivages|30 juin 2022",
        "Promotions|LCBO|Aeroplan 8 Pack Offer",
        "Promotions|Last Chance",
        "Promotion|Dernière chance",
        "Promotion|LCBO|Offre pack de huit Aeroplan",
        "Products|Beer & Cider|Ale|Stout & Porter|Imperial Stout",
        "Produits|Bière et cidre|Ale|Stout et porter|Imperial Stout",
        "Produits|Vin|Vin de spécialité|Vin de fruit",
        "May 12 2022",
        "Products|Beer & Cider|Gifts and Samplers|Gift Packs",
        "Products|Wine|Specialty Wine|Fruit Wine",
        "Produits|Bière et cidre|Cadeau et emballage mixte|Ensemble-cadeau de bière et de cidre",
        "Vintages|Vintages - Exclusivités en ligne|12 mai 2022",
        "Products|Beer & Cider|Lager|Pale Lager|Czech-Style Pilsner",
        "Products|Spirits|Whisky|Japanese & International Whiskey",
        "Produits|Bière et cidre|Lager|Lager pâle|Pilsen de style tchèque",
        "Produits|Spiritueux|Whisky|Whisky japonais et international",
        "Vintages|Vintages en vacances",
        "Vintages|Vintages on Vacation",
        "New Arrivals|Coolers",
        "Nouveaux arrivages|Cooler",
        "Products|Spirits|Rum|Spiced Rum",
        "Produits|Spiritueux|Rhum|Rhum épicé",
        "Collections|Vin|Festival des vins de Toronto|Californie",
        "Collections|Wine|Wine Fest Toronto|California",
        "Products|Spirits|Liqueur|Coffee Liqueur",
        "Produits|Spiritueux|Liqueur|Liqueur de café",
        "Cadeaux|Prix|Moins de 25 $",
        "Gifts|Shop by Price|Under $25",
        "Products|Beer & Cider|Ale|Stout & Porter|Dry Stout",
        "Produits|Bière et cidre|Ale|Stout et porter|Stout sec",
        "Promotions|One Day Sale|Canada Day",
        "Promotion|Solde d'un jour|La fête du Canada",
        "Cadeaux|Cadeaux de mariage|Moins de 50 $",
        "Products|Spirits|Vodka|Flavoured Vodka|Fruit",
        "Produits|Spiritueux|Vodka|Vodka aromatisée|Vodka aromatisée aux fruits",
        "Collections|Vin|Californie",
        "Collections|Wine|California",
        "Gifts|Wedding Gifts|Under $50",
        "Collections|Occasions|Cadeau pour la fête des pères|Spiritueux",
        "Collections|Occasions|Gifts for Father's Day|Spirit",
        "Products|Beer & Cider|Ale|Pale Ale|Blonde Pale Ale",
        "Products|Coolers|Coolers & Cocktails|Light Coolers",
        "Products|Spirits|Cognac & Brandy|Cognac|XO Cognac",
        "Products|Spirits|Tequila|Añejo Tequila",
        "Produits|Bière et cidre|Ale|Ale pâle|Ale pâle blonde",
        "Produits|Cooler|Cooler et cocktail|Cooler léger",
        "Produits|Spiritueux|Cognac et brandy|Cognac|Cognac XO",
        "Produits|Spiritueux|Tequila|Tequila anejo",
        "Vintages|Vintages - Exclusivités en ligne|Exclusivités en ligne de Vintages - Livraison du 2 juin 2022",
        "Vintages|Vintages - Online Exclusives",
        "Vintages|Vintages - Online Exclusives|Online Exclusives - Vintages Release June 2 2022",
        "Products|Beer & Cider|Ale|Sour Ale|Fruited Sour Ale",
        "Products|Spirits|Whisky|Scotch Whisky|Island Single Malt Scotch Whisky",
        "Produits|Bière et cidre|Ale|Ale sure|Ale sure aux fruits",
        "Produits|Spiritueux|Whisky|Whisky écossais|Scotch single malt d'Island",
        "Promotions|Clearance|Clearance Wines",
        "Promotion|Liquidation|Liquidation Vin",
        "Collections|Occasions|Cadeau pour la fête des pères|Vin",
        "Collections|Occasions|Gifts for Father's Day|Wine",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)|New England IPA",
        "Products|Beer & Cider|Ale|Wheat Ale|Belgian Witbier",
        "Produits|Bière et cidre|Ale|Ale de blé|Witbier belge",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)|IPA de style Nouvelle-Angleterre",
        "Collections|Spirits|Discover Hendrick's Neptunia",
        "Collections|Spiritueux|Découvrir Hendrick's Neptunia",
        "Products|Spirits|Cognac & Brandy|Cognac|V.S.O.P. Cognac",
        "Products|Spirits|Gin|Flavoured Gin|Fruit Flavoured Gin",
        "Products|Spirits|Rum|White Rum",
        "Produits|Spiritueux|Cognac et brandy|Cognac|Cognac V.S.O.P.",
        "Produits|Spiritueux|Gin|Gin aromatisé|Gin aromatisé aux fruits",
        "Produits|Spiritueux|Rhum|Rhum blanc",
        "Promotions|LCBO|Best Deals",
        "Promotion|LCBO|Meilleures aubaines",
        "Products|Beer & Cider|Ale|Wheat Ale|American Wheat Ale",
        "Products|Spirits|Cognac & Brandy|Armagnac",
        "Products|Spirits|Gin|Flavoured Gin|Citrus Flavoured Gin",
        "Produits|Bière et cidre|Ale|Ale de blé|Ale de blé américaine",
        "Produits|Spiritueux|Cognac et brandy|Armagnac",
        "Produits|Spiritueux|Gin|Gin aromatisé|Gin aromatisé aux agrumes",
        "Collections|Spirits|Tropical Spirits",
        "Collections|Spiritueux|Spiritueux Tropicaux",
        "Products|Beer & Cider|Ale|Stout & Porter|Sweet Stout",
        "Products|Beer & Cider|Ale|Wheat Ale|Weizen",
        "Products|Spirits|Cognac & Brandy|Brandy|V.S.O.P. Brandy",
        "Produits|Bière et cidre|Ale|Ale de blé|Weizen",
        "Produits|Bière et cidre|Ale|Stout et porter|Stout douce",
        "Produits|Spiritueux|Cognac et brandy|Brandy|Brandy V.S.O.P.",
        "Collections|Coolers|Fruity Coolers",
        "Collections|Coolers|Mixed Packs",
        "Collections|Cooler|Carton mixte",
        "Collections|Cooler|Coolers Fruites",
        "Products|Coolers|Teas",
        "Produits|Cooler|Thé",
        "Cadeaux|Sacs-cadeaux et boîtes",
        "Collections|Spirits|Canadian Whiskies",
        "Collections|Spiritueux|Canadian Whiskies",
        "Collections|Tendances|Voyez la vie en rose",
        "Collections|Trends|Pink Picks",
        "Gifts|Gift Bags & Boxes",
        "Products|Beer & Cider|Lager|Amber Lager|Vienna Lager",
        "Products|Spirits|Tequila|Mezcal",
        "Produits|Bière et cidre|Lager|Lager ambrée|Lager viennoise",
        "Produits|Spiritueux|Tequila|Mezcal",
        "Collections|Fierté",
        "Collections|Pride",
        "Collections|Spirits|Ontario Small Distillers|Shop Local Gin",
        "Collections|Spirits|Ontario Small Distillers|Shop Local Vodka",
        "Collections|Spirits|Shop More Tequilas",
        "Collections|Spiritueux|Acheter Plus De Tequilas",
        "Collections|Spiritueux|Local Gin",
        "Collections|Spiritueux|Local Vodka",
        "Collections|Tendances| Vins Canadiens",
        "Collections|Trends|Canadian Wines",
        "Products|Spirits|Rum|White Rum|Classic White Rum",
        "Produits|Spiritueux|Rhum|Rhum blanc|Rhum blanc classique",
        "Promotions|Free Home Delivery on Select Online Exclusives",
        "Collections|Coolers|Tropical Coolers",
        "Collections|Cooler|cooler tropicales",
        "Collections|Tendances|Citron vif",
        "Collections|Trends|Lively Lemon",
        "Products|Beer & Cider|Ale|Pale Ale|Amber Ale",
        "Products|Spirits|Cognac & Brandy|Brandy|V.S. Brandy",
        "Products|Spirits|Whisky|American Whiskey & Bourbon|American Rye Whiskey",
        "Products|Spirits|Whisky|Canadian Whisky|Canadian Flavoured Whisky",
        "Products|Spirits|Whisky|Japanese & International Whiskey|Japanese & International Blended Whisky",
        "Products|Wine|Fortified Wine|New World Fortified Wine",
        "Produits|Bière et cidre|Ale|Ale pâle|Ale ambrée",
        "Produits|Spiritueux|Cognac et brandy|Brandy|Brandy V.S.",
        "Produits|Spiritueux|Whisky|Whiskey américain et bourbon|Whiskey de seigle américain",
        "Produits|Spiritueux|Whisky|Whisky canadien|Whisky canadien aromatisé",
        "Produits|Spiritueux|Whisky|Whisky japonais et international|Whisky d'assemblage japonais et international",
        "Produits|Vin|Vin fortifié|Vin fortifié Nouveau Monde",
        "Vintages|Exclusivités en ligne|Moins de 50 $",
        "Vintages|Online Exclusives|Under $50",
        "Cadeaux|Cadeaux de mariage|Moins de 100 $",
        "Collections|Coolers|Summer Favourites",
        "Gifts|Wedding Gifts|Under $100",
        "Products|Beer & Cider|Ale|Dark Ale|Brown Ale",
        "Products|Beer & Cider|Ale|Dark Ale|Scottish Ale",
        "Products|Beer & Cider|Ale|Lagered Ale|Cream Ale",
        "Produits|Bière et cidre|Ale|Ale foncée|Ale brune",
        "Produits|Bière et cidre|Ale|Ale foncée|Ale écossaise",
        "Produits|Bière et cidre|Ale|Lager-ale|Cream Ale",
        "Promotions|One Day Sale|Canada Day|Spirits",
        "Promotion|Solde d'un jour|La fête du Canada|Spiritueux",
        "Collections|Canadian Made",
        "Collections|Fabriqués au canada",
        "Collections|Spirits|Whisky Shop|American Whiskey",
        "Collections|Spiritueux|Boutique De Whisky|American Whiskey",
        "Collections|Vin|Vins mousseux en petit format",
        "Collections|Wine|Small Format Sparkling Wines",
        "Products|Beer & Cider|Ale|Pale Ale|Golden Pale Ale",
        "Products|Beer & Cider|Lager|Pale Lager|Strong Lager",
        "Products|Spirits|Gin|Traditional Gin|American Gin",
        "Produits|Bière et cidre|Ale|Ale pâle|Ale pâle dorée",
        "Produits|Bière et cidre|Lager|Lager pâle|Lager forte",
        "Produits|Spiritueux|Gin|Gin traditionnel|Gin américain",
        "Promotions|Last Chance|Spirits",
        "Promotion|Dernière chance|Spiritueux",
        "April 14 2022",
        "Collections|Beer & Cider|Game Day Beers",
        "Collections|Beer & Cider|Summer Favourites",
        "Collections|Beer & Cider|Tropics",
        "Collections|Bière et cidre|Favoris d'été",
        "Collections|Bière et cidre|Jour De Jeu Biere",
        "Collections|Coolers|Cooler Sampler Packs",
        "Collections|Cooler|Coolers - Carton mixte",
        "Products|Beer & Cider|Ale|Dark Ale|Barrel Aged Ale",
        "Products|Beer & Cider|Ale|Sour Ale|Dry Hopped Sour Ale",
        "Products|Beer & Cider|Non-Alcoholic & Specialty|Non-Alcoholic Beer",
        "Products|Spirits|Liqueur|Sippers & Mixers|Orange",
        "Products|Spirits|Vodka|Flavoured Vodka|Lemonade & Citrus",
        "Produits|Bière et cidre|Ale|Ale foncée|Ale vieillie en fût",
        "Produits|Bière et cidre|Ale|Ale sure|Ale sure houblonnée à cru",
        "Produits|Bière et cidre|Bière de spécialité|Bière sans alcool",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur|Boisson à siroter et allongeur à l'orange",
        "Produits|Spiritueux|Vodka|Vodka aromatisée|Vodka aromatisée aux agrumes",
        "Vintages|Vintages - Exclusivités en ligne|14 avril 2022",
        "Products|Beer & Cider|Ale|Belgian Ale|Belgian Dark Ale",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)|English IPA",
        "Products|Beer & Cider|Ale|Pale Ale|English Bitter Ale",
        "Products|Coolers|Caesars",
        "Products|Spirits|Liqueur|Bitters|Amaro",
        "Products|Spirits|Rum|Amber & Dark Rum|Amber Rum",
        "Produits|Bière et cidre|Ale|Ale belge|Ale belge foncée",
        "Produits|Bière et cidre|Ale|Ale pâle|Bitter ale anglaise",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)|IPA anglaise",
        "Produits|Cooler|César",
        "Produits|Spiritueux|Liqueur|Amer|Amaro",
        "Produits|Spiritueux|Rhum|Rhum ambré ou brun|Rhum ambré",
        "Vintages|Vintages - Moins de 15 $",
        "Vintages|Vintages Under $15",
        "Collections|Spirits|Whisky Shop|Irish Whiskey",
        "Collections|Spiritueux|Boutique De Whisky|Irish Whiskey",
        "Collections|Tendances|Bières et vins allégés",
        "Collections|Trends|Lighter Beer and Wine",
        "Collections|Vin|Vins blanc d'été",
        "Collections|Wine|Summer White Wines",
        "Products|Spirits|Cognac & Brandy|Brandy|Tsipouro",
        "Products|Spirits|Cognac & Brandy|Cognac|V.S. Cognac",
        "Products|Spirits|Gin|Traditional Gin|Classic Gin",
        "Products|Spirits|Liqueur|Bitters|Sambuca & Ouzo",
        "Products|Spirits|Liqueur|Sippers & Mixers|Cinnamon",
        "Products|Spirits|Rum|Flavoured Rum",
        "Produits|Spiritueux|Cognac et brandy|Brandy|Tsipouro",
        "Produits|Spiritueux|Cognac et brandy|Cognac|Cognac V.S.",
        "Produits|Spiritueux|Gin|Gin traditionnel|Gin classique",
        "Produits|Spiritueux|Liqueur|Amer|Sambuca et Ouzo",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur|Boisson à siroter at allongeur à la cannelle",
        "Produits|Spiritueux|Rhum|Rhum aromatisé",
        "Collections|LCBO|Celebrity Products|Wines",
        "Collections|LCBO|Produits de noms célèbres|Vin",
        "Collections|Tendances|Options aux cerises",
        "Collections|Trends|Cherry Picks",
        "Products|Beer & Cider|Ale|Belgian Ale|Belgian Pale Ale",
        "Products|Beer & Cider|Ale|Pale Ale|English Pale Ale",
        "Products|Beer & Cider|Ale|Sour Ale|Gose",
        "Products|Spirits|Premixed Cocktails",
        "Products|Spirits|Tequila|Gold & Silver Tequila",
        "Products|Spirits|Whisky|Canadian Whisky|Canadian Rye Whisky",
        "Products|Spirits|Whisky|Japanese & International Whiskey|Japanese & International Single Malt Whisky",
        "Produits|Bière et cidre|Ale|Ale belge|Ale pâle belge",
        "Produits|Bière et cidre|Ale|Ale pâle|Ale pâle anglaise",
        "Produits|Bière et cidre|Ale|Ale sure|Gose",
        "Produits|Spiritueux|Cocktail prémélangé",
        "Produits|Spiritueux|Tequila|Tequila gold et silver",
        "Produits|Spiritueux|Whisky|Whisky canadien|Whisky de seigle canadien",
        "Produits|Spiritueux|Whisky|Whisky japonais et international|Whisky pur malt japonais et international",
        "Vintages|Rosé - Vintages",
        "Vintages|Vintage Rose",
        "Collections|Tendances|Sangria",
        "Collections|Trends|Sangria",
        "Collections|Vin|Festival des vins de Toronto|Afrique du Sud",
        "Collections|Wine|Wine Fest Toronto|South Africa",
        "Products|Beer & Cider|Ale|Sour Ale|Lambic",
        "Products|Beer & Cider|Lager|Amber Lager|Marzen & Oktoberfest",
        "Products|Beer & Cider|Lager|Pale Lager|Asian Lager",
        "Products|Spirits|Rum|Amber & Dark Rum|Gold Rum",
        "Produits|Bière et cidre|Ale|Ale sure|Lambic",
        "Produits|Bière et cidre|Lager|Lager ambrée|Marzen et oktoberfest",
        "Produits|Bière et cidre|Lager|Lager pâle|Lager asiatique",
        "Produits|Spiritueux|Rhum|Rhum ambré ou brun|Rhum doré",
        "Promotions|Last Chance|Wines",
        "Promotion|Dernière chance|Vin",
        "Collections|Beer & Cider|Cider Favourites",
        "Collections|Beer & Cider|Fruity Beer",
        "Collections|Beer & Cider|Tropical Beers",
        "Collections|Bière et cidre|Biere Fruites",
        "Collections|Bière et cidre|Cidre favoris",
        "Collections|Bière et cidre|bieres tropicales",
        "Collections|Occasions|J.P. Wiser’s & Molson Legends",
        "Collections|Occasions|Légendes de J.P. Wiser et Molson",
        "Collections|Tendances|Saveurs d’aromates",
        "Collections|Trends|Botanical Flavours",
        "Collections|Vin|Festival des vins de Toronto| Chili",
        "Collections|Vin|Festival des vins de Toronto| L'Europe",
        "Collections|Vin|Vins à servir lors d’un mariage|Vin mousseux et Champagne",
        "Collections|Wine|Wine Fest Toronto|Chile",
        "Collections|Wine|Wine Fest Toronto|Europe",
        "Collections|Wine|Wines to Serve at Your Wedding|Sparkling Wines and Champagne",
        "Products|Beer & Cider|Ale|Sour Ale|Berliner Weisse",
        "Products|Beer & Cider|Lager|Dark Lager|Schwarzbier",
        "Products|Spirits|Cognac & Brandy|Brandy|XO Brandy",
        "Products|Spirits|Liqueur|Bitters|Arak & Raki",
        "Products|Spirits|Liqueur|Sippers & Mixers|Honey",
        "Products|Spirits|Rum|Amber & Dark Rum|Dark Rum",
        "Products|Spirits|Whisky|Irish Whiskey|Irish Single Malt Whiskey",
        "Products|Wine|Icewine|Red Icewine",
        "Produits|Bière et cidre|Ale|Ale sure|Berliner Weisse",
        "Produits|Bière et cidre|Lager|Lager foncée|Schwarzbier",
        "Produits|Spiritueux|Cognac et brandy|Brandy|Brandy XO",
        "Produits|Spiritueux|Liqueur|Amer|Arak et raki",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur|Boisson à siroter et allongeur au miel",
        "Produits|Spiritueux|Rhum|Rhum ambré ou brun|Rhum brun",
        "Produits|Spiritueux|Whisky|Whiskey irlandais|Whiskey pur malt irlandais",
        "Produits|Vin|Vin de glace|Vin de glace rouge",
        "Promotions|LCBO|Special Occasion Products",
        "Promotion|LCBO|Produits pour occasions spéciales",
        "Vintages|Vintages en vacances|faibles en sucre",
        "Vintages|Vintages on Vacation|Low Sugar",
        "Collections|Beer & Cider|New Craft Beers",
        "Collections|Bière et cidre|Nouvelle bière artisanale",
        "Collections|Spirits|Lighter Choice Spirits",
        "Collections|Spiritueux|Choix Alleges",
        "Collections|Tendances|Cocktails Prémélangés",
        "Collections|Trends|One Pour Cocktails",
        "Products|Beer & Cider|Ale|Dark Ale|Irish Red Ale",
        "Products|Spirits|Whisky|American Whiskey & Bourbon|American Blended Whiskey",
        "Produits|Bière et cidre|Ale|Ale foncée|Ale rousse irlandaise",
        "Produits|Spiritueux|Whisky|Whiskey américain et bourbon|Whiskey d'assemblage américain",
        "Collections|Spirits|Flavoured Spirits",
        "Collections|Spirits|UK Gins",
        "Collections|Spiritueux|Spiritueux Aromatises",
        "Collections|Spiritueux|UK Gins",
        "Products|Beer & Cider|Cider|Mixed Pack Cider",
        "Products|Spirits|Whisky|American Whiskey & Bourbon|Tennessee Whiskey",
        "Products|Wine|Gifts and Samplers|White Wine Gifts and Samplers",
        "Produits|Bière et cidre|Cidre|Carton mixte de cidre",
        "Produits|Spiritueux|Whisky|Whiskey américain et bourbon|Whiskey du Tennessee",
        "Produits|Vin|Cadeau et emballage mixte|Cadeau / Emballage mixte de vin blanc",
        "Vintages|Vintages - Exclusivités en ligne|Exclusivités en ligne de Vintages - Livraison du 2 juin 2022|Vins pour un BBQ",
        "Vintages|Vintages - Online Exclusives|Online Exclusives - Vintages Release June 2 2022|Wines for a BBQ",
        "Collections|Coolers|Local Ready to Drink",
        "Collections|Cooler|Prêt-à-boire locale",
        "Collections|Spirits|Local Spirits",
        "Collections|Spirits|Spring Cocktails",
        "Collections|Spiritueux|Cocktails Printaniers",
        "Collections|Spiritueux|Spiritueux locaux",
        "Collections|Tendances|agrumes",
        "Collections|Trends|Citrus",
        "Collections|Vin|Vins biologique",
        "Collections|Vin|Vins à servir lors d’un mariage|Accords avec des plats de bœuf",
        "Collections|Vin|Vins à servir lors d’un mariage|Accords avec des plats végétariens",
        "Collections|Virtual Events",
        "Collections|Virtual Events|Join Our Virtual Events - April",
        "Collections|Wine|Organic Wines",
        "Collections|Wine|Wines to Serve at Your Wedding|Pairings for Beef",
        "Collections|Wine|Wines to Serve at Your Wedding|Pairings for Vegetarian",
        "Collections|dégustations Virtuelles",
        "Collections|dégustations Virtuelles|Joignez-vous à nos dégustations virtuelles - Avril",
        "Products|Beer & Cider|Ale|Belgian Ale|Belgian Tripel",
        "Products|Beer & Cider|Ale|Stout & Porter|Oatmeal Stout",
        "Products|Beer & Cider|Lager|Dark Lager|Dunkel",
        "Products|Spirits|Liqueur|Sippers & Mixers|Limoncello",
        "Products|Spirits|Vodka|Flavoured Vodka|Savoury",
        "Produits|Bière et cidre|Ale|Ale belge|Tripel belge",
        "Produits|Bière et cidre|Ale|Stout et porter|Stout à l'avoine",
        "Produits|Bière et cidre|Lager|Lager foncée|Dunkel",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur|Limoncello",
        "Produits|Spiritueux|Vodka|Vodka aromatisée|Vodka au goût umami",
        "Promotions|Clearance|Clearance Spirits",
        "Promotions|One Day Sale|Victoria Day",
        "Promotion|Liquidation|Liquidation Spiritueux",
        "Promotion|Solde d'un jour|Fête de la Reine",
        "Collections|Beer & Cider|Premium Picks",
        "Collections|Bière et cidre|Haut de gamme",
        "Collections|Spirits|Ontario Small Distillers|Shop Local Whisky",
        "Collections|Spiritueux|Local Whisky",
        "Products|Spirits|Cognac & Brandy|Armagnac|Hors d'age Armagnac",
        "Products|Spirits|Soju|Flavoured Soju",
        "Produits|Spiritueux|Cognac et brandy|Armagnac|Armagnac Hors d'âge",
        "Produits|Spiritueux|Soju|Soju aromatisé",
        "Promotions|Buy a Case for Free Home Delivery",
        "Promotion|Achetez une caisse et bénéficiez de la livraison à domicile gratuite",
        "Vintages|Exclusivités en ligne|Moins de 100 $",
        "Vintages|Online Exclusives|Under $100",
        "Collections|Occasions|Sparkling",
        "Collections|Occasions|Summer Hot List",
        "Collections|Occasions|Vin mousseux",
        "Collections|Occasions|Vos favoris de l’été",
        "Collections|Spirits|Summer Favourites",
        "Collections|Spiritueux|Favoris de l’été",
        "Collections|Tendances|Framboise Bleue",
        "Collections|Trends|Blue Raspberry",
        "Collections|Vin|Festival des vins de Toronto| Argentine",
        "Collections|Vin|Vins en petit récipient",
        "Collections|Vin|Vins à servir lors d’un mariage|Accords avec des plats de fruits de mer",
        "Collections|Vin|Vins à servir lors d’un mariage|Accords avec des plats de volaille",
        "Collections|Wine|Portable Picks",
        "Collections|Wine|Wine Fest Toronto|Argentina",
        "Collections|Wine|Wines to Serve at Your Wedding|Pairings for Chicken",
        "Collections|Wine|Wines to Serve at Your Wedding|Pairings for Seafood",
        "New Arrivals|New Arrivals",
        "Nouveaux arrivages|Nouveaux arrivages",
        "Products|Beer & Cider|Ale|Belgian Ale|Belgian Blonde Ale",
        "Products|Beer & Cider|Ale|Pale Ale|Extra Special Bitter (ESB)",
        "Products|Beer & Cider|Lager|Dark Lager|Traditional Bock",
        "Products|Spirits|Liqueur|Sippers & Mixers|Amaretto",
        "Products|Spirits|Vodka|Flavoured Vodka|Dessert",
        "Products|Spirits|Whisky|American Whiskey & Bourbon|American Flavoured Whiskey",
        "Products|Spirits|Whisky|Scotch Whisky|Lowland Single Malt Scotch Whisky",
        "Produits|Bière et cidre|Ale|Ale belge|Ale belge blonde",
        "Produits|Bière et cidre|Ale|Ale pâle|Extra Special Bitter (ESB)",
        "Produits|Bière et cidre|Lager|Lager foncée|Bière bock traditionnelle",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur|Amaretto",
        "Produits|Spiritueux|Vodka|Vodka aromatisée|Vodka à saveur de dessert",
        "Produits|Spiritueux|Whisky|Whiskey américain et bourbon|Whiskey américain aromatisé",
        "Produits|Spiritueux|Whisky|Whisky écossais|Scotch single malt des Lowlands",
        "Promotions|One Day Sale|Canada Day|Wine",
        "Promotion|Solde d'un jour|La fête du Canada|Vin",
        "Vintages|Vintages - Exclusivités en ligne|Exclusivités en ligne de Vintages - Livraison du 2 juin 2022|Vins pour Brunch",
        "Vintages|Vintages - Online Exclusives|Online Exclusives - Vintages Release June 2 2022|Wines for Brunch",
        "Vintages|Vintages en vacances|Moins de 25",
        "Vintages|Vintages on Vacation|Gifts Under 25",
        "Cadeaux|Cadeaux de mariage|Moins de 25 $",
        "Collections|Coolers|New Coolers for Summer",
        "Collections|Cooler|Nouveaux arrivages d'ete",
        "Collections|Spirits|Gifting Rums",
        "Collections|Spiritueux|Rhums Cadeaux",
        "Collections|Tendances|Touche Tropicale",
        "Collections|Trends|Tropical Tastes",
        "Collections|Vin|Coffrets decouverte de vins",
        "Collections|Wine|Wine Discovery Boxes",
        "Gifts|Wedding Gifts|Under $25",
        "Products|Beer & Cider|Ale|Flavoured & Spiced Beer|Pumpkin Ale",
        "Products|Beer & Cider|Ale|Stout & Porter|Irish Stout",
        "Products|Beer & Cider|Lager|Dark Lager|Doppelbock",
        "Produits|Bière et cidre|Ale|Bière aromatisée et bière épicée|Ale à la citrouille",
        "Produits|Bière et cidre|Ale|Stout et porter|Stout irlandais",
        "Produits|Bière et cidre|Lager|Lager foncée|Doppelbock",
        "Promotions|Coolers",
        "Vintages|Exclusivités en ligne|Moins de 25 $",
        "Vintages|Online Exclusives|Under $25",
        "Vintages|Vintages en vacances|Biologique",
        "Vintages|Vintages on Vacation|Organic",
        "Collections|LCBO|Celebrity Products|Beers",
        "Collections|LCBO|Produits de noms célèbres|Bière et cidre",
        "Collections|Occasions|Cadeau pour la fête des pères|Bières",
        "Collections|Occasions|Gifts for Father's Day|Beer",
        "Collections|Spirits|Game Day Spirits",
        "Collections|Spirits|Whisky Shop|Canadian Whisky",
        "Collections|Spiritueux|Boutique De Whisky|Canadian Whisky",
        "Collections|Spiritueux|Jour De Jeu Spirits",
        "Products|Beer & Cider|Non-Alcoholic & Specialty|Mead",
        "Products|Spirits|Whisky|Canadian Whisky|Canadian Single Malt Whisky",
        "Produits|Bière et cidre|Bière de spécialité|Hydromel",
        "Produits|Spiritueux|Whisky|Whisky canadien|Whisky pur malt canadien",
        "Cadeaux|Cadeaux de mariage|Cadeaux de luxe",
        "Collections|Beer & Cider|Last Chance",
        "Collections|Bière et cidre|Dernière chance",
        "Collections|Spirits|Jose Cuervo",
        "Collections|Spirits|Whisky Shop|Whisky Shop Seasonal Favourites",
        "Collections|Spiritueux|Boutique De Whisky|Incontournables De La Saison",
        "Collections|Tendances|Sodas aux aromates",
        "Collections|Trends|Botanical Seltzers",
        "Collections|Vin|Festival des vins de Toronto|Région - Niagara-on-the-Lake",
        "Collections|Wine|Wine Fest Toronto|Niagara on the Lake",
        "Gifts|Wedding Gifts|Luxe Gifts",
        "Products|Beer & Cider|Ale|Belgian Ale|Belgian Dubbel",
        "Products|Beer & Cider|Ale|Dark Ale|Red Ale",
        "Produits|Bière et cidre|Ale|Ale belge|Dubbel belge",
        "Produits|Bière et cidre|Ale|Ale foncée|Ale rousse",
        "Promotions|Beer & Cider",
        "Promotions|Beer & Cider|Last Chance Beer",
        "Promotions|Coolers|Twisted Tea",
        "Promotions|Long Weekend Super Sale",
        "Promotion|Bière et cidre",
        "Promotion|Bière et cidre|Dernière chance bière",
        "Collections|Coolers|Craft Beer Sampler Packs",
        "Collections|Cooler|Bière artisanale - Carton mixte",
        "Collections|Occasions|Father's Day",
        "Collections|Occasions|Father's Day|Beer",
        "Collections|Occasions|Fête des Pères",
        "Collections|Occasions|Fête des Pères|Bière",
        "New Arrivals|New Arrivals|Wines",
        "Nouveaux arrivages|Nouveaux arrivages|Vins",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)|Black IPA",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)|Milkshake IPA",
        "Products|Beer & Cider|Ale|India Pale Ale (IPA)|Sour IPA",
        "Products|Beer & Cider|Ale|Lagered Ale|Altbier",
        "Products|Coolers|Coolers & Cocktails|Shots",
        "Products|Spirits|Cognac & Brandy|Armagnac|Napoleon Armagnac",
        "Products|Spirits|Cognac & Brandy|Armagnac|V.S.O.P. Armagnac",
        "Products|Spirits|Cognac & Brandy|Brandy|Calvados",
        "Products|Spirits|Cognac & Brandy|Brandy|Sliovica",
        "Products|Spirits|Liqueur|Bitters|Cocktail Bitters",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)|IPA noire",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)|IPA sure",
        "Produits|Bière et cidre|Ale|India Pale Ale (IPA)|Milkshake IPA",
        "Produits|Bière et cidre|Ale|Lager-ale|Altbier",
        "Produits|Cooler|Cooler et cocktail|Cul-sec",
        "Produits|Spiritueux|Cognac et brandy|Armagnac|Armagnac Napoléon",
        "Produits|Spiritueux|Cognac et brandy|Armagnac|Armagnac V.S.O.P.",
        "Produits|Spiritueux|Cognac et brandy|Brandy|Calvados",
        "Produits|Spiritueux|Cognac et brandy|Brandy|Slivovitz",
        "Produits|Spiritueux|Liqueur|Amer|Amer à cocktail",
        "Promotions|Buy a Case for Free Home Delivery|Buy 12 for Free Home Delivery",
        "Promotions|Last Chance|Beers and Coolers",
        "Promotions|One Day Sale|Victoria Day|Spirits",
        "Promotion|Achetez une caisse et bénéficiez de la livraison à domicile gratuite|Vin achetez 12 et beneficiez de la livraison a domicile gratuite",
        "Promotion|Dernière chance|Bière cidre et cooler",
        "Promotion|Solde d'un jour|Fête de la Reine|Spiritueux",
        "Vintages|Vintages - Exclusivités en ligne|Exclusivités en ligne de Vintages - Livraison du 2 juin 2022|Vins pour le jardin",
        "Vintages|Vintages - Online Exclusives|Online Exclusives - Vintages Release June 2 2022|Backyard Sippers",
        "Collections|Beer & Cider|Lighter Local Beers",
        "Collections|Beer & Cider|Local Beer",
        "Collections|Bière et cidre|Bière locale",
        "Collections|Coolers|Boxed Coolers",
        "Collections|Cooler|Coolers dans une boîte",
        "Collections|Spirits|Sazerac",
        "Collections|Spiritueux|Sazerac",
        "Collections|Tendances|Ale pâle dorée",
        "Collections|Trends|Golden Beers",
        "Products|Beer & Cider|Ale|Belgian Ale|Belgian Farmhouse Ale",
        "Products|Beer & Cider|Ale|Belgian Ale|Belgian Quadrupel",
        "Products|Beer & Cider|Ale|Belgian Ale|Belgian Strong Ale",
        "Products|Beer & Cider|Ale|Pale Ale|Rye Ale",
        "Products|Beer & Cider|Non-Alcoholic & Specialty|Gluten-Free Beer",
        "Products|Spirits|Cognac & Brandy|Armagnac|XO Armagnac",
        "Products|Spirits|Liqueur|Sippers & Mixers|Cassis",
        "Products|Spirits|Rum|Amber & Dark Rum|Black Rum",
        "Products|Spirits|Whisky|Canadian Whisky|Canadian Spiced Whisky",
        "Products|Spirits|Whisky|Scotch Whisky|Campbeltown Single Malt Scotch Whisky",
        "Produits|Bière et cidre|Ale|Ale belge|Ale forte belge",
        "Produits|Bière et cidre|Ale|Ale belge|Farmhouse ale belge",
        "Produits|Bière et cidre|Ale|Ale belge|Quadrupel belge",
        "Produits|Bière et cidre|Ale|Ale pâle|Bière de seigle",
        "Produits|Bière et cidre|Bière de spécialité|Bière sans gluten",
        "Produits|Spiritueux|Cognac et brandy|Armagnac|Armagnac XO",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur|Boisson à siroter et allongeur au cassis",
        "Produits|Spiritueux|Rhum|Rhum ambré ou brun|Rhum noir",
        "Produits|Spiritueux|Whisky|Whisky canadien|Whisky canadien épicé",
        "Produits|Spiritueux|Whisky|Whisky écossais|Scotch single malt Campbeltown",
        "Vintages|Vintages en vacances|Les Cinq Plus Populaires",
        "Vintages|Vintages on Vacation|Top Five",
        "Collections|Spirits|Irish Whiskey",
        "Collections|Spirits|Whisky Shop|Japanese Whisky",
        "Collections|Spiritueux|Boutique De Whisky|Japanese Whisky",
        "Collections|Spiritueux|Whiskey irlandais",
        "Collections|Tendances|Cidre",
        "Collections|Trends|Refreshing Cider",
        "New Arrivals|New Arrivals|Beer & Cider",
        "Nouveaux arrivages|Nouveaux arrivages|Cidres et bières",
        "Products|Beer & Cider|Ale|Flavoured & Spiced Beer|Spiced Beer",
        "Products|Beer & Cider|Lager|Amber Lager|American Amber Lager",
        "Products|Coolers|Coolers & Cocktails|Frozen Pouches",
        "Products|Spirits|Gin|Flavoured Gin|Premixed Gin Cocktails",
        "Products|Spirits|Liqueur|Bitters|Absinthe",
        "Products|Wine|Gifts and Samplers|Dessert Wine Gifts and Samplers",
        "Produits|Bière et cidre|Ale|Bière aromatisée et bière épicée|Bière épicée",
        "Produits|Bière et cidre|Lager|Lager ambrée|Lager ambrée américaine",
        "Produits|Cooler|Cooler et cocktail|Sachet congelé",
        "Produits|Spiritueux|Gin|Gin aromatisé|Cocktail au gin prémélangé",
        "Produits|Spiritueux|Liqueur|Amer|Absinthe",
        "Produits|Vin|Cadeau et emballage mixte|Cadeau / Emballage mixte de vin de dessert",
        "Promotions|One Day Sale|Canada Day|Coolers",
        "Promotions|One Day Sale|Victoria Day|Wine",
        "Promotion|Solde d'un jour|Fête de la Reine|Vin",
        "Promotion|Solde d'un jour|La fête du Canada|Cooler",
        "Collections|LCBO|Celebrity Products|Coolers",
        "Collections|LCBO|Produits de noms célèbres|Cooler",
        "Collections|Occasions|Lightened Up Local Beers",
        "Collections|Occasions|Lighter Summer Wines",
        "Collections|Occasions|New Caesar Flavours",
        "Collections|Occasions|One Pour Cocktails",
        "Products|Beer & Cider|Ale|Dark Ale|Barleywine",
        "Products|Beer & Cider|Ale|Dark Ale|English Brown Ale",
        "Products|Spirits|Liqueur|Sippers & Mixers|Ginger",
        "Products|Spirits|Rum|White Rum|Cachaça",
        "Products|Wine|Icewine|Sparkling Icewine",
        "Produits|Bière et cidre|Ale|Ale foncée|Ale brune anglaise",
        "Produits|Bière et cidre|Ale|Ale foncée|Vin d'orge",
        "Produits|Spiritueux|Liqueur|Boisson à siroter et allongeur|Boisson à siroter et allongeur au gingembre",
        "Produits|Spiritueux|Rhum|Rhum blanc|Cachaça",
        "Produits|Vin|Vin de glace|Vin de glace mousseux",
        "Promotions|Buy a Case for Free Home Delivery|Buy 24 for Free Home Delivery",
        "Promotion|Achetez une caisse et bénéficiez de la livraison à domicile gratuite|Cooler achetez 24 et beneficiez de la livraison a domicile gratuite",
        "Vintages|Vintages - Exclusivités en ligne|Exclusivités en ligne de Vintages - Livraison du 2 juin 2022|Autre",
        "Vintages|Vintages - Online Exclusives|Online Exclusives - Vintages Release June 2 2022|Other",
        "Vintages|Vintages en vacances|Les Nouveaux Essentiels",
        "Vintages|Vintages on Vacation|Newest Essentials",
        "Collections|Coolers|Truly",
        "Collections|Spirits|818 Tequila",
        "Collections|Spiritueux|818 Tequila",
        "Products|Beer & Cider|Lager|Dark Lager|Czech Dark Lager",
        "Products|Beer & Cider|Lager|Dark Lager|Maibock",
        "Products|Coolers|Coolers & Cocktails|Cream-Based",
        "Products|Spirits|Cognac & Brandy|Brandy|Akvavit",
        "Products|Spirits|Rum|White Rum|Overproof White Rum",
        "Produits|Bière et cidre|Lager|Lager foncée|Lager brune tchèque",
        "Produits|Bière et cidre|Lager|Lager foncée|Maibock",
        "Produits|Cooler|Cooler et cocktail|À base de crème",
        "Produits|Spiritueux|Cognac et brandy|Brandy|Akvavit",
        "Produits|Spiritueux|Rhum|Rhum blanc|Rhum blanc overproof",
        "Promotions|Buy a Case for Free Home Delivery|Buy 6 for Free Home Delivery",
        "Promotions|Coolers|Truly",
        "Promotions|One Day Sale|Victoria Day|Coolers",
        "Promotion|Achetez une caisse et bénéficiez de la livraison à domicile gratuite|Bière achetez 24 et beneficiez de la livraison a domicile gratuite",
        "Promotion|Solde d'un jour|Fête de la Reine|Cooler",
        "Products|Beer & Cider|Ale|Flavoured & Spiced Beer|Gruit",
        "Products|Beer & Cider|Ale|Lagered Ale|California Common",
        "Products|Beer & Cider|Ale|Lagered Ale|Steam Beer",
        "Products|Beer & Cider|Ale|Wheat Ale|Dunkelweizen",
        "Products|Beer & Cider|Lager|Dark Lager|Rauchbier",
        "Products|Spirits|Cognac & Brandy|Brandy|Kirsch",
        "Products|Spirits|Gin|Flavoured Gin|Sloe Gin",
        "Products|Wine|Icewine|Mixed Pack Icewine",
        "Produits|Bière et cidre|Ale|Ale de blé|Dunkelweizen",
        "Produits|Bière et cidre|Ale|Bière aromatisée et bière épicée|Gruit",
        "Produits|Bière et cidre|Ale|Lager-ale|California Common",
        "Produits|Bière et cidre|Ale|Lager-ale|Steam Beer",
        "Produits|Bière et cidre|Lager|Lager foncée|Rauchbier",
        "Produits|Spiritueux|Cognac et brandy|Brandy|Kirsh",
        "Produits|Spiritueux|Gin|Gin aromatisé|Gin à la prunelle",
        "Produits|Vin|Vin de glace|Emballage mixte de vin de glace",
        "Promotions|Clearance|Clearance Beers",
        "Promotion|Liquidation|Liquidation Biere",
        "Vintages|Exclusivités en ligne|Vins de luxe",
        "Vintages|Online Exclusives|Luxe"
    ];
    public const THE_BIG_KAHUNAS = [
        "Products|Beer & Cider",
        "Products|Spirits",
        "Products|Coolers",
        "Products|Wine|Red Wine",
        "Products|Wine|White Wine",
        "Products|Wine|Sparkling Wine",
        "Products|Wine|Rose Wine",
        "Products|Wine|Fortified Wine",
        "Products|Wine|Champagne",
    ];

    // todo refactor blacklisted ids to be config values?
    public const BLACKLISTED_IDS = [
        21514,
        27049, // smirnoff
        28009, // georgian bay + sunglasses (#1)
    ];

    use HasFactory;

    protected $primaryKey = 'permanent_id';

    protected $fillable = [
        'title',
        'brand',
        'category',
        'subcategory',
        'price',
        'volume',
        'alcohol_content',
        'price_index',
        'country',
        'url',
        'thumbnail_url',
        'image_url',
        'rating',
        'out_of_stock',
        'description',
        'reviews',
        'permanent_id'
    ];

}
